"use client";

import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapActivation from "@/helpers/BootstrapActivation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AccountContext, IAccountInfo } from "@/contex/AccountContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//	title: "Create Next App",
//	description: "Generated by create next app",
//};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const [accountInfo, setAccountInfo] = useState<IAccountInfo | undefined>();

	const updateAccountInfo = (value: IAccountInfo) => {
		setAccountInfo(value);
		localStorage.setItem("_token", value.token!);
	};
	return (
		<html lang="en">
			<body>
				<AccountContext.Provider
					value={{
						accountInfo: accountInfo,
						setAccountInfo: updateAccountInfo,
					}}
				>
					<Header />
					<main className="appContainer"> {children}</main>
					<Footer />
					<BootstrapActivation />
				</AccountContext.Provider>
			</body>
		</html>
	);
}
